GET http://localhost:3000/users

###
GET http://localhost:3000/users/?id=64d230ac9c3865e2208bb733


###
GET http://localhost:3000/users/?userID=yomama@111


###
DELETE http://localhost:3000/users/64d22cc29c3865e2208bb721


###
DELETE http://localhost:3000/users/


###
PATCH http://localhost:3000/users/64d2306a9c3865e2208bb72f
Content-Type: application/json

{
    "credentials" :{
        "email" : "supdude@gmail.com"
    },
    "data" : {
        "username" : "I_am_the_danger_Skyler"
    }
}


###
GET http://localhost:3000/users/otp/sudhinkarki20@gmail.com


###
POST http://localhost:3000/users/
Content-Type: application/json

{
    "credentials" : {
        "email" : "pas077bct042@wrc.edu.np",
        "password" : "mynameisjeff69"
    },
    "data" : {
        "username" : "Jeff"
    }
}


