GET http://localhost:3000/users/

###
GET http://localhost:3000/users?id=64d230ac9c3865e2208bb733


###
GET http://localhost:3000/users/?userID=jeff@123


###
DELETE http://localhost:3000/users/64d22cc29c3865e2208bb721


###
DELETE http://localhost:3000/users/


###
PATCH http://localhost:3000/users/id:64ce3e4d0ab8ba874611be23
Content-Type: application/json

{
    "data" : {
        "username" : "NotTheRealJeff"
    }
}


###
POST http://localhost:3000/users/
Content-Type: application/json

{
    "credentials" : {
        "userID" : "jeff@111",
        "email" : "sunx.sapk@gmail.com",
        "password" : "mynameisjeff69"
    },
    "data" : {
        "username" : "Jeff"
    }
}
